"""Builds the real control register + reports from real, live-generated
evidence artifacts — the actual "evidence generated by CI, not written
by hand" pipeline, run end to end.

Ingests: atlas's, atlas-control's, and atlas-retrieval's real `pytest
--junitxml` output, atlas-control's real `opa test --format json`
output, the real committed `evidence/findings.duckdb`, and (if present)
Project 4's committed `phase3_results.json`.

Deliberately does *not* bring up atlas-detect's live ClickHouse/Collector
stack — that's Docker-heavy and out of scope for this lightweight,
CI-runnable script. The two detection-derived controls
(`detection-tool-denial-visibility`, `detection-plan-deviation`) are
refreshed by a separate, documented manual step (see the README): bring
up the stack, run `uv run --package atlas-detect pytest packages/
atlas-detect --junitxml=evidence/assurance/_artifacts/
atlas_detect_junit.xml`, and this script picks that file up on its next
run if it exists. Until then the register correctly reports those two
controls as `not_assessed` rather than silently skipping them.

    uv run --package atlas-assurance python packages/atlas-assurance/scripts/build_register.py
"""

from __future__ import annotations

import json
import subprocess
from datetime import UTC, datetime
from pathlib import Path

from atlas_assurance.executive_summary import render_executive_summary
from atlas_assurance.ingest.findings import load_findings
from atlas_assurance.ingest.junit import parse_junit
from atlas_assurance.ingest.opa import parse_opa_json
from atlas_assurance.models import TestResult
from atlas_assurance.register import REPO_ROOT, build_register
from atlas_assurance.report import render_assurance_report
from atlas_assurance.trend import build_trend, render_trend_report

ARTIFACTS_DIR = REPO_ROOT / "evidence" / "assurance"
ARTIFACTS_TMP_DIR = ARTIFACTS_DIR / "_artifacts"
REGISTER_PATH = ARTIFACTS_DIR / "control_register.json"
REPORT_PATH = REPO_ROOT / "evidence" / "reports" / "atlas_assurance_report.html"
EXEC_SUMMARY_PATH = REPO_ROOT / "evidence" / "reports" / "atlas_assurance_executive_summary.html"
TREND_PATH = REPO_ROOT / "evidence" / "reports" / "atlas_assurance_trend.html"


def _run_pytest_junit(package: str, path: Path, junit_path: Path) -> list[TestResult]:
    subprocess.run(
        ["uv", "run", "--package", package, "pytest", str(path), "-q", f"--junitxml={junit_path}"],
        cwd=REPO_ROOT,
        check=True,
    )
    return parse_junit(junit_path, package=package)


def _run_opa_json(policy_dir: Path, opa_json_path: Path) -> list[TestResult]:
    result = subprocess.run(
        ["opa", "test", str(policy_dir), "--format", "json"],
        cwd=REPO_ROOT,
        check=True,
        capture_output=True,
        text=True,
    )
    opa_json_path.write_text(result.stdout)
    return parse_opa_json(opa_json_path, ingested_at=datetime.now(UTC))


def main() -> None:
    ARTIFACTS_TMP_DIR.mkdir(parents=True, exist_ok=True)

    test_results: list[TestResult] = []
    test_results += _run_pytest_junit(
        "atlas", REPO_ROOT / "packages" / "atlas", ARTIFACTS_TMP_DIR / "atlas_junit.xml"
    )
    test_results += _run_pytest_junit(
        "atlas-control",
        REPO_ROOT / "packages" / "atlas-control",
        ARTIFACTS_TMP_DIR / "atlas_control_junit.xml",
    )
    test_results += _run_pytest_junit(
        "atlas-retrieval",
        REPO_ROOT / "packages" / "atlas-retrieval",
        ARTIFACTS_TMP_DIR / "atlas_retrieval_junit.xml",
    )
    test_results += _run_opa_json(
        REPO_ROOT / "packages" / "atlas-control" / "policy", ARTIFACTS_TMP_DIR / "opa_control.json"
    )

    # Picked up only if a previous manual, Docker-backed atlas-detect run
    # left it here (see this module's docstring) — never generated by this
    # script, and never faked when absent.
    detect_junit = ARTIFACTS_TMP_DIR / "atlas_detect_junit.xml"
    if detect_junit.exists():
        test_results += parse_junit(detect_junit, package="atlas-detect")
        print(f"Ingested pre-existing atlas-detect evidence from {detect_junit}")
    else:
        print(
            f"No {detect_junit.name} present — atlas-detect's two detection controls will be "
            "reported as not_assessed (see README)."
        )

    findings = load_findings()
    generated_at = datetime.now(UTC)
    register = build_register(test_results, findings, generated_at=generated_at)

    previous_register = json.loads(REGISTER_PATH.read_text()) if REGISTER_PATH.exists() else None
    REGISTER_PATH.write_text(json.dumps(register, indent=2, default=str))

    REPORT_PATH.parent.mkdir(parents=True, exist_ok=True)
    REPORT_PATH.write_text(render_assurance_report(register))
    EXEC_SUMMARY_PATH.write_text(render_executive_summary(register, previous_register))

    trend_points = build_trend(findings)
    TREND_PATH.write_text(render_trend_report(trend_points))

    print(f"Wrote {REGISTER_PATH}")
    print(f"Wrote {REPORT_PATH}")
    print(f"Wrote {EXEC_SUMMARY_PATH}")
    print(f"Wrote {TREND_PATH}")
    print(
        f"\n{register['controls_assessed']} assessed, "
        f"{register['controls_not_assessed']} not assessed, "
        f"{register['controls_stale']} stale."
    )


if __name__ == "__main__":
    main()
